apiVersion: argocd-image-updater.argoproj.io/v1alpha1
kind: ImageUpdater
metadata:
  name: petclinic-helm-image-updater
  namespace: argocd
spec:
  applicationRefs:
    - namePattern: petclinic-helm
      useAnnotations: true
